import React, { useState, useEffect } from 'react';
import { Button } from "@/components/ui/button"

export default function DisclaimerPopup() {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const hasSeenDisclaimer = localStorage.getItem('hasSeenDisclaimer');
    if (!hasSeenDisclaimer) {
      setIsOpen(true);
    }
  }, []);

  const handleAgree = () => {
    localStorage.setItem('hasSeenDisclaimer', 'true');
    setIsOpen(false);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-gray-800 p-8 rounded-lg max-w-2xl w-full mx-4">
        <h2 className="text-2xl font-bold text-white mb-4">Welcome to anione.ai! 👋</h2>
        
        <h3 className="text-xl font-semibold text-white mb-2">⚠️ Important Disclaimer:</h3>
        <h4 className="text-lg font-semibold text-white mb-2">Content Responsibility:</h4>
        <ul className="list-disc list-inside text-gray-300 mb-4">
          <li>The pictures and text generated during chats are created by AI and may contain inappropriate information.</li>
          <li>anione.ai is not responsible for the content generated by the AI, including any unexpected or sensitive outputs.</li>
          <li>Users are encouraged to use the service responsibly and avoid sharing personal, sensitive, or harmful information in conversations.</li>
        </ul>
                
        <p className="text-gray-300 mb-4">By continuing, you agree to our Terms of Use and Privacy Policy.</p>
        
        <Button 
          onClick={handleAgree}
          className="w-full bg-white text-black hover:bg-gray-200 transition-colors"
        >
          Agree
        </Button>
      </div>
    </div>
  );
}